name: add nomount
description: add and configure nomount

runs:
  using: composite
  steps:
   - name: run setup script
     shell: bash
     run: |
      cd "$COMMON"
      curl https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/dev/kernel/setup.sh | bash -

   - name: add to defconfig
     shell: bash
     run: |
      "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NOMOUNT
